{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes-agent.fullname" . }}
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config.yaml | nindent 4 }}
{{- end }}
